package com.brace.examverse.data;

import org.json.JSONException;
import org.json.JSONObject;

public class StudyTask {
    public long id;
    public long examId;
    public long topicId;
    public String title;
    public long dueAt;
    public int minutes;
    public int priority;
    public boolean done;
    public boolean autoGenerated;

    public StudyTask(long id, long examId, long topicId, String title, long dueAt, int minutes,
                     int priority, boolean done, boolean autoGenerated) {
        this.id = id; this.examId = examId; this.topicId = topicId; this.title = title;
        this.dueAt = dueAt; this.minutes = Math.max(5, minutes); this.priority = Math.max(1, Math.min(5, priority));
        this.done = done; this.autoGenerated = autoGenerated;
    }

    public JSONObject toJson() throws JSONException {
        JSONObject o = new JSONObject();
        o.put("id", id); o.put("examId", examId); o.put("topicId", topicId); o.put("title", title);
        o.put("dueAt", dueAt); o.put("minutes", minutes); o.put("priority", priority); o.put("done", done);
        o.put("autoGenerated", autoGenerated); return o;
    }

    public static StudyTask fromJson(JSONObject o) {
        return new StudyTask(o.optLong("id", System.currentTimeMillis()), o.optLong("examId", -1),
                o.optLong("topicId", -1), o.optString("title", "Study task"),
                o.optLong("dueAt", System.currentTimeMillis()), o.optInt("minutes", 30),
                o.optInt("priority", 3), o.optBoolean("done", false), o.optBoolean("autoGenerated", false));
    }
}
